name: Cron Job

on:
  repository_dispatch:
    types: [build]
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install pandas requests
      - run: python .ci_support/social.py
        env:
          YOUTUBEKEY: ${{ secrets.YOUTUBEKEY }}
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: main
          folder: .
